name: DePloY
on:
  push:
    branches:
      - master
    paths:
      - "**.ts"
      - "**.json"
jobs:
  UpdatePresences:
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'PreMiD'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          cache: "yarn"
      - name: Prep PU
        run: yarn
      - name: Update Presences
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: yarn pu
